[tool.black]
line-length = 120
target-version = ['py35' , 'py36' , 'py37' , 'py38' , 'py39']
exclude = '''
	/(
	| .git
	| .github
	| pyproject.toml
	| setup.cfg
	)\
	'''

[tool.isort]
line_length = 120
multi_line_output = 3
include_trailing_comma = true
use_parentheses = true
lines_after_imports = 2
lines_between_types = 1
skip = [".git", ".github", "pyproject.toml", "setup.cfg"]
